/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 22 05:45:27 GMT 2019
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.FizzBuzz3;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FizzBuzz3_ESTest extends FizzBuzz3_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FizzBuzz3 fizzBuzz3_0 = new FizzBuzz3();
      String string0 = fizzBuzz3_0.fizzBuzz(835);
      assertEquals("Buzz", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FizzBuzz3 fizzBuzz3_0 = new FizzBuzz3();
      String string0 = fizzBuzz3_0.fizzBuzz(296);
      assertEquals("296", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FizzBuzz3 fizzBuzz3_0 = new FizzBuzz3();
      String string0 = fizzBuzz3_0.fizzBuzz(582);
      assertEquals("Fizz", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FizzBuzz3 fizzBuzz3_0 = new FizzBuzz3();
      // Undeclared exception!
      try { 
        fizzBuzz3_0.fizzBuzz((-36));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tutorial.FizzBuzz3", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FizzBuzz3 fizzBuzz3_0 = new FizzBuzz3();
      String string0 = fizzBuzz3_0.fizzBuzz(2670);
      assertEquals("FizzBuzz", string0);
  }
}
