/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 22 05:27:53 GMT 2019
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.MaxNum;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MaxNum_ESTest extends MaxNum_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MaxNum maxNum0 = new MaxNum();
      int int0 = maxNum0.maxNum(1, 1, 1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MaxNum maxNum0 = new MaxNum();
      int int0 = maxNum0.maxNum(19, (-492), 1998);
      assertEquals(1998, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MaxNum maxNum0 = new MaxNum();
      int int0 = maxNum0.maxNum(1, 0, 0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MaxNum maxNum0 = new MaxNum();
      int int0 = maxNum0.maxNum(0, 1, (-5182));
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MaxNum maxNum0 = new MaxNum();
      int int0 = maxNum0.maxNum(0, (-2173), 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MaxNum maxNum0 = new MaxNum();
      int int0 = maxNum0.maxNum(0, (-538), (-1220));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MaxNum maxNum0 = new MaxNum();
      int int0 = maxNum0.maxNum((-3978), (-3978), (-1));
      assertEquals((-1), int0);
  }
}
