/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 22 05:36:09 GMT 2019
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.TestResult;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TestResult_ESTest extends TestResult_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TestResult testResult0 = new TestResult();
      String string0 = testResult0.testResult(21, 90);
      assertEquals("pass", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TestResult testResult0 = new TestResult();
      String string0 = testResult0.testResult(90, 33);
      assertEquals("pass", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TestResult testResult0 = new TestResult();
      String string0 = testResult0.testResult(130, 0);
      assertEquals("pass", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TestResult testResult0 = new TestResult();
      String string0 = testResult0.testResult(60, 60);
      assertEquals("pass", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TestResult testResult0 = new TestResult();
      String string0 = testResult0.testResult(60, 1607);
      assertEquals("pass", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TestResult testResult0 = new TestResult();
      String string0 = testResult0.testResult(58, 58);
      assertEquals("failure", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TestResult testResult0 = new TestResult();
      String string0 = testResult0.testResult(107, 0);
      assertEquals("pass", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      TestResult testResult0 = new TestResult();
      String string0 = testResult0.testResult(0, 100);
      assertEquals("pass", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      TestResult testResult0 = new TestResult();
      String string0 = testResult0.testResult(1649, 21);
      assertEquals("pass", string0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      TestResult testResult0 = new TestResult();
      String string0 = testResult0.testResult(0, 0);
      assertEquals("failure", string0);
  }
}
